/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iVB87RoWf1b
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function CardBlog() {
  return (
    <Card className="flex items-center gap-6 p-6 rounded-lg shadow-lg">
      <img
        src="/placeholder.svg"
        alt="Product Image"
        width={300}
        height={300}
        className="rounded-lg object-cover aspect-square"
      />
      <div className="space-y-2">
        <h3 className="text-2xl font-bold">Elegant Leather Backpack</h3>
        <p className="text-muted-foreground">A stylish and durable leather backpack perfect for everyday use.</p>
        <div className="flex items-center gap-2">
          <TagIcon className="w-5 h-5 text-primary" />
          <span className="text-lg font-semibold">$99.99</span>
        </div>
        <Button size="sm">Add to Cart</Button>
      </div>
    </Card>
  )
}

function TagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" />
      <circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />
    </svg>
  )
}
