/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zbSokpVTOgn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function CardBlogH() {
  return (
    <Card className="flex flex-row items-center gap-6 bg-primary p-6 rounded-lg shadow-sm border border-white">
      <img
        src="/img_test.webp"
        alt="Card Image"
        className="w-[300px] h-[200px] rounded-lg object-cover"
        width="300"
        height="200"
        style={{ aspectRatio: "300/200", objectFit: "cover" }}
      />
      <div className="space-y-2">
        <h3 style={{ color: 'white' }} className="text-2xl font-semibold text-white">Unlock Your Potential</h3>
        <p className="text-muted-foreground">Discover how our platform can help you achieve your goals.</p>
        <div className="flex items-center gap-4">
        <div className="flex justify-end  ">
          <Button className="mt-2 w-full text-lg font-bold  bg-[#f87171] style={{ color: 'white' }}" >Ver mas</Button>
        </div>
          <Link href="#" className="text-sm text-primary hover:underline" prefetch={false}>
            Learn More
          </Link>
        </div>
      </div>
    </Card>
  )
}
