/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dLFZxQMEZZ2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function ContactPage() {
  return (
    <div className="dark:bg-muted dark:text-foreground">
      {/* <header className="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur-sm dark:bg-muted/80">
        <div className="container mx-auto flex h-14 max-w-5xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="#" className="flex items-center gap-2 font-semibold" prefetch={false}>
            <PenIcon className="h-6 w-6" />
            <span>Personal Blog</span>
          </Link>
          <nav className="flex items-center gap-4 md:gap-6 lg:gap-8">
            <Link
              href="#"
              className="rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground dark:hover:bg-background"
              prefetch={false}
            >
              Home
            </Link>
            <Link
              href="#"
              className="rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground dark:hover:bg-background"
              prefetch={false}
            >
              About
            </Link>
            <Link
              href="#"
              className="rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground dark:hover:bg-background"
              prefetch={false}
            >
              Contact
            </Link>
          </nav>
        </div>
      </header> */}
      <main className="container mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 gap-8 md:grid-cols-[2fr_1fr] lg:gap-12">
          <div>
            <article className="prose dark:prose-invert">
              <h1>Welcome to my Personal Blog</h1>
              <p>
                This is where I share my thoughts, experiences, and insights on a variety of topics. Feel free to
                explore and let me know what you think!
              </p>
              <h2>Recent Posts</h2>
              <ul>
                <li>
                  <Link href="#" className="font-medium hover:underline" prefetch={false}>
                    The Importance of Self-Care
                  </Link>
                </li>
                <li>
                  <Link href="#" className="font-medium hover:underline" prefetch={false}>
                    Navigating the Challenges of Remote Work
                  </Link>
                </li>
                <li>
                  <Link href="#" className="font-medium hover:underline" prefetch={false}>
                    Discovering the Joy of Minimalism
                  </Link>
                </li>
              </ul>
            </article>
          </div>
          <div className="space-y-8 md:space-y-10 lg:space-y-12">
            <Card>
              <CardHeader>
                <CardTitle>Schedule an Appointment</CardTitle>
                <CardDescription>Book a session with me to discuss your goals and needs.</CardDescription>
              </CardHeader>
              <CardContent>
                <form className="space-y-4">
                  <div className="space-y-1">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="Enter your name" />
                  </div>
                  <div className="space-y-1">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" type="email" placeholder="Enter your email" />
                  </div>
                  <div className="space-y-1">
                    <Label htmlFor="date">Date</Label>
                    <Input id="date" type="date" />
                  </div>
                  <div className="space-y-1">
                    <Label htmlFor="time">Time</Label>
                    <Input id="time" type="time" />
                  </div>
                  <Button type="submit" className="w-full">
                    Book Appointment
                  </Button>
                </form>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>About the Author</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-4">
                  <Avatar className="h-16 w-16 border-2 border-primary">
                    <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">John Doe</div>
                    <div className="text-muted-foreground">Personal Blogger</div>
                  </div>
                </div>
                <p className="mt-4">
                  Hi, I'm John Doe, a passionate personal blogger who loves to share my thoughts and experiences with
                  the world. I'm here to inspire, educate, and connect with like-minded individuals.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}

function PenIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
    </svg>
  )
}
