/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3B4qSjZ1ViJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function CardTitle({ image, title }: { image: string; title: string }) {
  return (
    <Card className="w-full h-full relative text-white rounded-lg overflow-hidden">
      <img
        src={image} //"/img_test.webp"
        alt={title} //"Promotional Video Editing"
        className="w-full h-full object-cover"
        width="300"
        height="300"
        style={{ aspectRatio: "300/300", objectFit: "cover" }}
      />
      <div className="absolute inset-0 bg-gradient-to-t from-[rgba(0,0,0,1)] to-[rgba(0,0,0,0)] flex flex-col justify-end p-4">
        <p style={{ color: 'white' }} className="text-white mb-0 text-lg font-bold">{title}</p>
      </div>

    </Card>
  )
}
