/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hSRPOiPcnIp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { CardTitle } from "./card-title"

export function CardServices({ image, title, description, link }: { image: string; title: string; description: string; link: string }) {
  return (
    <div className="w-[20.75rem] h-[25rem] p-5">
      <Card className="text-white">
        <div className="relative h-full pl-2 pr-2">
          <CardHeader className="h-full pl-4 pr-4">
            <CardTitle
              image={image}
              title={title}
            />
          </CardHeader>
        </div>
        <CardFooter className="flex flex-col">
          <p style={{ color: 'white' }} className="text-white text-xs">{description}</p>
          {/* <ButtonWithLink link={link} /> */}

          {/* <a href={link} target="_blank" rel="noopener noreferrer"> 'https://google.com' */}

          <Button className="mt-2 w-full text-lg font-bold  bg-[#f87171] style={{ color: 'white' }}" >Agendar</Button>
          {/* </a> */}

        </CardFooter>
      </Card>
    </div>
  )
}
