/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YEnkhTT5VUm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'
import { Arimo } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"
import { JSX, SVGProps } from "react"
import Image from "next/image"
import { CardServices } from "./card-services"
import { CardTitle } from "./card-title"
import { NavBarResp } from "./nav-bar-resp"
import FooterService from "./footer"
import { useEffect, useState } from 'react';
import AsiTrabajamos from "./section-pasos"

export function HomePage() {

  const [users, setUsers] = useState({});
  useEffect(() => {
    const fetchUsers = async () => {
      const response = await fetch('/api/hello');
      const data = await response.json();
      setUsers(data);
    };

    fetchUsers();
  }, []);

  const addUser = async (newUser) => {
    const response = await fetch('/api/hello', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(newUser),
    });

    if (response.ok) {
      const updatedUsers = await response.json();
      setUsers(updatedUsers);
    } else {
      console.error('Error adding user:', response.statusText);
    }
  };

  return (
    <div className="flex flex-col min-h-dvh">
      {/* <header className="bg-personalizado-secundary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <Image src="/icon-web.webp" width={40} height={40} />
            <Image src="/Publicidad-banner.webp" width={280} height={60} />
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="#" className="flex flex-col items-center justify-center text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              <HomeIcon className="w-5 h-5 mb-2" text-personalizado-background />
              Home
            </Link>
            <Link href="#" className="flex flex-col items-center justify-center text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              <BriefcaseIcon className="w-5 h-5 mb-2" />
              Job
            </Link>
            <Link href="#" className="flex flex-col items-center justify-center text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              <BookIcon className="w-5 h-5 mb-2" />
              Blog
            </Link>
            <Link href="#" className="flex flex-col items-center justify-center text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              <MailOpenIcon className="w-5 h-5 mb-2" />
              Contact
            </Link>
          </nav>
          <div className="relative">
            <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
              <SearchIcon className="h-4 w-4" />
            </div>
            <Input
              type="search"
              placeholder="Search news and blog"
              className="pl-10 pr-4 py-2 rounded-md bg-primary/20 focus:bg-primary/30 focus:outline-none"
            />
          </div>
        </div>
      </header> */}
      <NavBarResp />
      <main className="bg-personalizado-background flex-1 md:px-6 "> {/* bg-personalizado-background */}
        <div className="container mx-auto w-full grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 sm:justify-items-center pt-8 mt-14">

          <CardServices
            image="/paginas web.webp"
            title="Páginas web, con tráfico orgánico"
            description="Aumentamos el tráfico orgánico que recibe tú página mediante la creación y publicación de contenido para tú página."
            link="https:google.com"

          />

          <CardServices
            image="/redes sociales.webp"
            title="Contenido que Convierte: Redes Sociales"
            description="Capturamos la atención de tu audiencia en redes sociales con contenido creativo y estratégico, diseñado para aumentar tu engagement y seguidores."
            link="https:google.com"

          />
          <CardServices
            image="/edicion de video.webp"
            title="Vídeos TikTok que Viralizan: Edición Profesional"
            description="Transforma tus ideas en videos cortos y atractivos para TikTok, optimizados para alcanzar la máxima visibilidad."
            link="https:google.com"

          />
          <CardServices
            image="/asesorias.webp"
            title="Asesorias"
            description="Recibe asesoría personalizada respecto a programación y edición de video."
            link="https:google.com"

          />

        </div>
        {/*         <div>
          <h1>Json </h1>
          {users[0] ? (
            <div>
              <p>Nombre: {users[0].nombre} </p>
            </div>
          ) : (
            <p>No hay aun</p>
          )}
        </div>

        <div>
          <h1>Users</h1>

          <button onClick={() => addUser({ nombre: 'Nuevo Usuario' })}>
            Add User
          </button>
        </div> */}
        <br />
        <br />
        <AsiTrabajamos />
        <br />
        <br />
      </main>
      <FooterService />
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}

function LogoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M855 1590 l-176 -211 73 -68 c40 -37 88 -81 106 -97 l33 -29 -70 -72
-70 -73 -97 10 -96 10 -87 -79 c-123 -112 -191 -187 -191 -209 0 -10 18 -63
40 -118 l41 -99 -72 -146 c-74 -152 -80 -181 -37 -195 18 -5 14 -13 -46 -73
-36 -36 -66 -70 -66 -74 0 -9 1745 -5 1754 4 3 3 5 393 4 867 l-3 862 -235
-233 c-377 -372 -470 -462 -470 -455 0 4 19 29 43 55 23 27 82 97 130 156 l89
107 -69 64 c-157 145 -338 306 -345 306 -4 0 -86 -95 -183 -210z m175 -534
l52 -49 -193 -193 c-107 -107 -197 -194 -200 -194 -3 0 -9 48 -12 107 -8 144
-2 140 -172 117 l-40 -6 60 61 60 61 104 -6 104 -7 81 85 c47 50 86 83 92 80
7 -4 35 -29 64 -56z m-448 -377 c3 -71 6 -83 28 -101 l24 -19 -150 -150 c-82
-82 -152 -149 -156 -149 -4 0 25 66 64 146 l71 145 -36 90 c-19 49 -34 89 -34
90 3 1 160 26 173 28 8 1 13 -27 16 -80z"/>
      <path d="M613 1218 c-33 -16 -48 -61 -33 -98 15 -36 37 -50 77 -50 77 1 106
99 41 144 -26 18 -53 19 -85 4z"/>
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}



function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MailOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="none"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.2 8.4c.5.38.8.97.8 1.6v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V10a2 2 0 0 1 .8-1.6l8-6a2 2 0 0 1 2.4 0l8 6Z" />
      <path d="m22 10-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 10" />
    </svg>
  )
}