/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KbCYax31ukg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import React from 'react';
import Carousel from './carousel';

export function PageJob() {
  return (
    <div className="flex flex-col">
      <section className="bg-primary py-10 px-4 md:px-6">
        <div className="container mx-auto max-w-4xl">
          <h1 className="mb-10 text-center text-2xl font-bold text-primary-foreground">Quienes somos</h1>
          <div className="flex justify-center gap-8">
            <div className="flex flex-col items-center">
              <Avatar className="mb-4" style={{ borderRadius: '50%', overflow: 'hidden' }}>
                <AvatarImage
                  src="/img_test.webp"
                  alt="Team Member 1"
                  style={{ borderRadius: '50%', objectFit: 'cover' }}
                />
              </Avatar>
              <p className="text-sm text-muted-foreground">Desarrollador Elias Motilla. Con mas de 3 años de experiencia en el sector trabajando con tecnologías como html, css, js, Nest.js, react, flutter...

                <br /><br />Especialidad: Mobile, Web</p>
            </div>
            <div className="flex flex-col items-center">
              <Avatar className="mb-4" style={{ borderRadius: '50%', overflow: 'hidden' }}>
                <AvatarImage
                  src="/img_test.webp"
                  alt="Team Member 1"
                  style={{ borderRadius: '50%', objectFit: 'cover' }}
                />
              </Avatar>
              <p className="text-sm text-muted-foreground">Desarrollador Alvaro Gallo, con mas de 25 años de experiencia en desarrollo web y hosting trabajando en el sector con herramientas como Lavaravel, php, ...

                <br /><br />Especialidad: Web, hosting, servidores</p>
            </div>
            <div className="flex flex-col items-center">
              <Avatar className="mb-4" style={{ borderRadius: '50%', overflow: 'hidden' }}>
                <AvatarImage
                  src="/img-profile-carlos.webp"
                  alt="Team Member 1"
                  style={{ borderRadius: '50%', objectFit: 'cover' }}
                />
              </Avatar>
              <p className="text-sm text-muted-foreground">Desarrollador Carlos Peñaranda, con mas de 2 años de experiencia trabajando en el sector Mobile usando tecnologias como flutter, dart, kotlin...

                <br /><br />Especialidad: Mobile (Flutter, dart, kotlin), edicion multimedia (Capcut, Sony vegas, Premiere.).
              </p>

            </div>
          </div>


        </div>
      </section>


      <section className="py-10 md:py-20">
        <div className="container mx-auto max-w-5xl">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-1 lg:grid-cols-1">
            <div className="space-y-5">

              <Carousel />
            </div>
            <div className="space-y-2">

              <Carousel />
            </div>
            <div className="space-y-2">

              <Carousel />
            </div>
            <div className="space-y-2">

              <Carousel />
            </div>
            <div className="space-y-2">

              <Carousel />

              <h2 className="text-2xl font-bold">Creación de páginas web</h2>
              <h2 className="text-2xl font-bold">Trabajos realizados</h2>
              <h2 className="text-2xl font-bold">Creacion de contenido</h2>
              <h2 className="text-2xl font-bold">Restaruación de imagen</h2>
              <h2 className="text-2xl font-bold">Desarrollo de aplicaciones móviles</h2>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
