/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KbCYax31ukg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function PageJob() {
  return (
    <div className="flex flex-col">
      <section className="bg-primary py-10 px-4 md:px-6">
        <div className="container mx-auto max-w-5xl">
          <h1 className="mb-10 text-center text-2xl font-bold text-primary-foreground">Who We Are</h1>
          <div className="flex justify-center gap-8">
            <div className="flex flex-col items-center">
              <Avatar className="mb-4" style={{ borderRadius: '50%', overflow: 'hidden' }}>
                <AvatarImage
                  src="/img_test.webp"
                  alt="Team Member 1"
                  style={{ borderRadius: '50%', objectFit: 'cover' }}
                />
              </Avatar>
              <p className="text-sm text-muted-foreground">John Doe, CEO. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisi eu tincidunt aliquet, nunc nunc lacinia nunc, nec tincidunt nisl nunc nec nunc. Sed euismod, nunc nec.</p>
            </div>
            <div className="flex flex-col items-center">
              <Avatar className="mb-4" style={{ borderRadius: '50%', overflow: 'hidden' }}>
                <AvatarImage
                  src="/img_test.webp"
                  alt="Team Member 1"
                  style={{ borderRadius: '50%', objectFit: 'cover' }}
                />
              </Avatar>
              <p className="text-sm text-muted-foreground">Jane Smith, Designer. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisi eu tincidunt aliquet, nunc nunc lacinia nunc, nec tincidunt nisl nunc nec nunc. Sed euismod, nunc nec.</p>
            </div>
            <div className="flex flex-col items-center">
              <Avatar className="mb-4" style={{ borderRadius: '50%', overflow: 'hidden' }}>
                <AvatarImage
                  src="/img_test.webp"
                  alt="Team Member 1"
                  style={{ borderRadius: '50%', objectFit: 'cover' }}
                />
              </Avatar>
              <p className="text-sm text-muted-foreground">Bob Johnson, Developer. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisi eu tincidunt aliquet, nunc nunc lacinia nunc, nec tincidunt nisl nunc nec nunc. Sed euismod, nunc nec.</p>
            </div>
          </div>


        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container mx-auto max-w-5xl">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Web Page Creation</h2>
              <div className="grid grid-cols-3 gap-4">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Web Page 1"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Web Page 2"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Web Page 3"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Work Done</h2>
              <div className="grid grid-cols-3 gap-4">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Work 1"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Work 2"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Work 3"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Content Creation</h2>
              <div className="grid grid-cols-3 gap-4">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Content 1"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Content 2"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Content 3"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Image Restoration</h2>
              <div className="grid grid-cols-3 gap-4">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Image 1"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Image 2"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="Image 3"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">Application Creation</h2>
              <div className="grid grid-cols-3 gap-4">
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="App 1"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="App 2"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <img
                  src="/placeholder.svg"
                  width={200}
                  height={150}
                  alt="App 3"
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
